# Generated by Django 4.1.2 on 2023-08-04 17:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                ("name_ar", models.CharField(max_length=50)),
                ("is_movie", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=250)),
                ("year", models.IntegerField()),
                ("is_tvshow", models.BooleanField(default=False)),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=250)),
                ("year", models.IntegerField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
                ("link1", models.CharField(blank=True, max_length=250, null=True)),
                ("link2", models.CharField(blank=True, max_length=250, null=True)),
                ("link3", models.CharField(blank=True, max_length=250, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("number", models.CharField(max_length=8)),
                ("link1", models.CharField(blank=True, max_length=250, null=True)),
                ("link2", models.CharField(blank=True, max_length=250, null=True)),
                ("link3", models.CharField(blank=True, max_length=250, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "serie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.serie"
                    ),
                ),
            ],
        ),
    ]
