# Generated by Django 4.1.2 on 2023-05-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=250)),
                ("year", models.IntegerField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
                ("link1", models.CharField(blank=True, max_length=250, null=True)),
                ("link2", models.CharField(blank=True, max_length=250, null=True)),
                ("link3", models.CharField(blank=True, max_length=250, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "movies_category",
                    models.CharField(
                        choices=[
                            ("Globe", "افلام اجنبية"),
                            ("Arab", "افلام عربية"),
                            ("Hindi", "افلام هندية"),
                            ("Asian", "افلام اسيوية"),
                        ],
                        default="Globe",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
