# Generated by Django 4.1.2 on 2023-08-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="title_ar",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
