# Generated by Django 4.1.2 on 2023-05-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_category_remove_movie_movies_category_movie_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="name_ar",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
