# Generated by Django 4.1.2 on 2023-05-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_category_options_category_name_ar"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default=0, verbose_name=models.CharField(max_length=50)
            ),
            preserve_default=False,
        ),
    ]
