# Generated by Django 4.1.2 on 2023-05-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(),
        ),
    ]
