# Generated by Django 4.1.2 on 2023-07-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_movie_title_serie_episode"),
    ]

    operations = [
        migrations.AddField(
            model_name="serie",
            name="is_tvshow",
            field=models.BooleanField(default=False),
        ),
    ]
