# Generated by Django 4.1.2 on 2023-05-04 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="firt_name",
            new_name="first_name",
        ),
    ]
